### ISSUE TITLE
Compile webpack error

### ISSUE THREAD

**Issue by egin10** [andes2912/sekolahku#102]
Boleh bantu check untuk compile webpack terjadi error saat npm run dev.

Ini terjadi karena file SCSS dan JS tidak ditemukan pada folder `resources/`.
Mungkin ter-remove saat merge terakhir.

Terima kasih.
Sukse selalu.

**Comment by 4RSIM3R** [comment]
mas, itu bisa di solve dengan `php -S localhost:8000 -t public`
