### ISSUE TITLE
Error: Cannot find module Webpack mix 

### ISSUE THREAD

**Issue by MayangAsura** [andes2912/sekolahku#103]
![image](https://github.com/user-attachments/assets/cb09fc62-691f-4e81-abf6-059194bda42b)

mohon maaf kak, kalau errornya yang muncul seperti itu solved nya gimana ya kak? sudah browsing, solusinya dengan copy paste webpack.config.js di laravel-mix/setup/webpack.config.js ke folder root , cuma masih error yang sama.

pakai cara yang php -S localhost:8000 -t public, kalau hasilnya begina gimana kak?
![image](https://github.com/user-attachments/assets/cc062ae1-4345-437c-8685-5e48302b1230)

Terimakasih kak.

**Comment by andes2912** [comment]
> ![image](https://github.com/user-attachments/assets/cb09fc62-691f-4e81-abf6-059194bda42b)
> 
> 
> 
> mohon maaf kak, kalau errornya yang muncul seperti itu solved nya gimana ya kak? sudah browsing, solusinya dengan copy paste webpack.config.js di laravel-mix/setup/webpack.config.js ke folder root , cuma masih error yang sama.
> 
> 
> 
> pakai cara yang php -S localhost:8000 -t public, kalau hasilnya begina gimana kak?
> 
> ![image](https://github.com/user-attachments/assets/cc062ae1-4345-437c-8685-5e48302b1230)
> 
> 
> 
> 
> 
> 
> 
> Terimakasih kak.
> 
> 

Error ini saat run npm run Dev?
Coba step ini di skip ya,harusnya bisa

**Comment by MayangAsura** [comment]
bener kak ketika npm run dev

**Comment by andes2912** [comment]
> bener kak ketika npm run dev
> 
> 

Kalau gitu step npm run Dev lewatkan saja

**Comment by MayangAsura** [comment]
kalau di skip , next nya apa ya kak. maaf pemula ini kak.. terimakasih, 
kalau migrationnya sudah success, dan env nya

kalau runningnya dengan php -S localhost:8000 -t public? masih 404 kak, apa saya ada yang kurang step nya kak, mohon arahannya..
![image](https://github.com/user-attachments/assets/776a1105-26e5-47b6-9a65-e19fcd3b5c8f)


------------
saya coba dulu kak, sepertinya ada yang ke skip bbrpa file dan folder pas nge clone

**Comment by andes2912** [comment]
php artisan storage:link sudah dijalankan?
Kalau sudah coba run dengan php artisan serve

**Comment by MayangAsura** [comment]
sudah kak, alhamdulillah aman kak, ternyata tadi belum generate key nya
terimakasih kak..
![image](https://github.com/user-attachments/assets/70f92635-a075-4fc6-9b21-07e12469734f)
