### ISSUE TITLE
Error when running "npm run dev" in terminal

### ISSUE THREAD

**Issue by iFelzz** [andes2912/sekolahku#104]
$ npm run dev

> dev
> npm run development

> development
> mix

✖ Mix
  Compiled with some errors in 90.11ms

ERROR in /js/app
Module not found: Error: Can't resolve 'C:\laragon\www\sekolahku\resources\js\app.js' in 'C:\laragon\www\sekolahku'
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json"]'?

ERROR in /js/app
Module not found: Error: Can't resolve 'C:\laragon\www\sekolahku\resources\sass\app.scss' in 'C:\laragon\www\sekolahku'
Did you miss the leading dot in 'resolve.extensions'? Did you mean '[".*",".wasm",".mjs",".js",".jsx",".json"]' instead of '["*",".wasm",".mjs",".js",".jsx",".json"]'?

webpack compiled with 2 errors

**Comment by andes2912** [comment]
> $ npm run dev
> 
> > dev
> > npm run development
> 
> > development
> > mix
> 
> ✖ Mix Compiled with some errors in 90.11ms
> 
> ERROR in /js/app Module not found: Error: Can't resolve 'C:\laragon\www\sekolahku\resources\js\app.js' in 'C:\laragon\www\sekolahku' Did you miss the leading dot in 'resolve.extensions'? Did you mean '["._",".wasm",".mjs",".js",".jsx",".json"]' instead of '["_",".wasm",".mjs",".js",".jsx",".json"]'?
> 
> ERROR in /js/app Module not found: Error: Can't resolve 'C:\laragon\www\sekolahku\resources\sass\app.scss' in 'C:\laragon\www\sekolahku' Did you miss the leading dot in 'resolve.extensions'? Did you mean '["._",".wasm",".mjs",".js",".jsx",".json"]' instead of '["_",".wasm",".mjs",".js",".jsx",".json"]'?
> 
> webpack compiled with 2 errors

skip this command `npm run dev`
