### ISSUE TITLE
Data Pembayaran

### ISSUE THREAD

**Issue by arewtech** [andes2912/sekolahku#98]
aku mau bertanya untuk data pembayaran yang sudah di bayar kan jadinya status pembayaran di proses, nah untuk handle itu ada dimana? soalnya aku udh login semua role tetap ga ada di sidebarnya data untuk update status pembayaran menjadi paid, ya meskipun masih manual, atau emang flownya sampe situ aja untuk pembayaran?

![photo_2023-11-14_21-23-00](https://github.com/andes2912/sekolahku/assets/75215687/b44fac61-9edf-4093-9d88-03288b037009)

**Comment by andes2912** [comment]
> aku mau bertanya untuk data pembayaran yang sudah di bayar kan jadinya status pembayaran di proses, nah untuk handle itu ada dimana? soalnya aku udh login semua role tetap ga ada di sidebarnya data untuk update status pembayaran menjadi paid, ya meskipun masih manual, atau emang flownya sampe situ aja untuk pembayaran?
> 
> ![photo_2023-11-14_21-23-00](https://user-images.githubusercontent.com/75215687/282806912-b44fac61-9edf-4093-9d88-03288b037009.jpg)

Untuk proses pembayaran dari calon murid atau murid action nya ada di role bendahara mas. Disana nanti bendahara bisa melakukan action diterima atau tidak nya.
![Screenshot 2023-11-15 at 13 25 28](https://github.com/andes2912/sekolahku/assets/42151067/44ee0054-c8e8-4946-b1df-6844846de2e9)

**Comment by arewtech** [comment]
solved, tq mas
